### ISSUE TITLE
There is an inconsistent error message in the 2 spec files that causing 2 failing test

### ISSUE THREAD

**Issue by lennhy** [learn-co-students/rails-amusement-park-v-000#162]
Starting with
ride_spec line 43     expect(ride.take_ride).to eq("Sorry. You do not have enough tickets the #{attraction.name}.")
ride_spec line 43  expect(ride.take_ride).to eq("Sorry. You do not have enough tickets the #{attraction.name}. You are not tall enough to ride the #{attraction.name}.")

while in users_features
line 252     expect(page).to have_content("You do not have enough tickets to ride the #{@ferriswheel.name}")

user features line 242
expect(page).to have_content("You are not tall enough to ride the #{@teacups.name}")

both specs are contradicting each other

**Comment by gj** [comment]
Hi @lennhy !

Thanks for catching this. Fixed in 968ae547338568e07126c7b118a47b5061c24d89
