### ISSUE TITLE
The master branch is the same as the solution

### ISSUE THREAD

**Issue by wakenightRyu** [learn-co-students/rails-amusement-park-v-000#38]
I reported this issue to one of the Learn instructors during my pairing session. I deleted all the migrations, models, controllers so that all the tests were failing. Then I did the lab from scratch and got the tests passing. It's been 3 days since I reported this issue.

**Comment by alexisadorn** [comment]
Same issue!

**Comment by atxrenegade** [comment]
This is a duplicate of a previously documented issue

**Comment by drakeltheryuujin** [comment]
Hi there,

Issues with a lesson in the curriculum should be opened on the appropriate
repository in `learn-co-curriculum`. 

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that others will not encounter the same
problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. Thanks for contributing! 💙
