### ISSUE TITLE
The master branch is identical to the solution branch

### ISSUE THREAD

**Issue by bentonwong** [learn-co-students/rails-amusement-park-v-000#4]
The master branch contains answers from the solution branch.  Students are unable to work on it since it is completed.

**Comment by drakeltheryuujin** [comment]
Hi there,

Issues with a lesson in the curriculum should be opened on the appropriate
repository in `learn-co-curriculum`. 

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that others will not encounter the same
problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. Thanks for contributing! 💙
